#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $SCRIPT_DIR

python -m venv .venv
source ./.venv/Scripts/activate
pip install -r requirements.txt
flask db init
flask db stamp head
flask db migrate
flask db upgrade